testing the new git function

diff --git a/.config/zsh/functions b/.config/zsh/functions
--- a/.config/zsh/functions
+++ b/.config/zsh/functions
@@ -37,11 +37,36 @@ function get_commit_message() {
 
 # switch between the defined working directories.
 function switch_working_directory() {
-  echo "\ncalled from function\n"
-  cat ./directories
+  DIRECTORIES=~/.dotfiles/.config/zsh/directories
+  WORKING_DIRECTORIES=~/.dotfiles/.config/zsh/working_directories
+  WDIRS=$(cat $DIRECTORIES $WORKING_DIRECTORIES)
+  DIR=$(echo $WDIRS | cut -d'=' -f1 | fzf)
+  FULLPATH=$(echo $WDIRS | grep $DIR | cut -d'=' -f2)
+  if [ -d $FULLPATH ]; then
+    cd $FULLPATH
+  else
+    echo "'${FULLPATH}' doesn't exist."
+  fi
 }
 
-# switch between the local defined working directories.
-function switch_local_working_directory() {
+# add the current directory to the working directories list
+function add_to_working_directory() {
+  echo "you've entered ${DIR_NAME}"
+  #if ! [ -z "$dir_name" ]; then
+  #  echo "The name is empty"
+  #fi
+  #current_dir=$(pwd)
+  #echo $current_dir
+}
 
+# git add all, commit with a given argument and push changes
+function git_add_commit_push() {
+  if [ "${1}" ]; then
+    git add .
+    git commit -m $1
+    git push
+  else
+    echo "ERROR: no commit message."
+    echo "Usage: acp 'this is a commit message.'"
+  fi
 }
